version: '3'

volumes:
  database_data:
    driver: local

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./log/nginx:/var/log/nginx
      - ./data/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./data/nginx/sites-enabled:/etc/nginx/sites-enabled
      - ./data/nginx/sites.template:/etc/nginx/sites-available/sites.template
      - ./data/nginx/default/html:/var/www/html
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
    environment:
      - URL_HOST=${URL_HOST:-sl.xlab.blindside-dev.com}
    command: /bin/bash -c "envsubst '$$URL_HOST' < /etc/nginx/sites-available/sites.template > /etc/nginx/sites-enabled/sites.conf && while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g 'daemon off;'"

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
